rmit-news/config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  resources :users

  root 'items#index'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'

  post '/users' => 'users#create'

  get "newcomments" => "items#newcomments"

  get "submit" => "items#submit"

  get "/v0/item/" => "apiv0#show"

  post "/v0/item/create" => "apiv0#create"

  get '/about' => 'pages#about'

  resources :apiv0, :path => '/v0/item/'  do
    resources :v0, controller: :apiv0
  end
  resources :items, :path => 'news'  do
   resources :posts, controller: :items, type: 'Post'
   resources :comments, controller: :items, type: 'Comment'
 end
end

rmit-news/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_include_tag "jquery" %>
    <title>RmitNews</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <div>
                <a class="navbar-brand" style='padding-right: 2px;' > <img style='height:25px;' src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/RMIT_University_Logo.svg/2000px-RMIT_University_Logo.svg.png" alt="">  </a>
                <span class="newsFix"> news </span>
              </div>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class=""><%= link_to "Home", root_path %></li>
                <li><%= link_to "New Comments", newcomments_path %></li>
                <li><%= link_to "Submit", submit_path %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <% if current_user %>
                  <li><%= link_to "Logout", '/logout' %></li>
                <% else %>
                  <li><%= link_to 'Sign Up', '/signup' %></li>
                  <li class=""><%= link_to 'Login', '/login' %></li>
                <% end %>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>

    <div class="col-xs-12 fwTopmargin gutters bottomAvoid">
      <%= yield %>
    </div>
    <div class="stickyfooter ">
      <div class="linksContainer">
        <p class="whiteText centereText inline-block"><%= link_to "API", about_path %></p>
        <p style="display: inline-block; padding-left:20px;padding-right:20px;"> | </p>
        <p class="whiteText centereText inline-block"><%= link_to "About", about_path %></p>
      </div>

    </div>
  </body>
</html>
<!--  -->