rmit-news/config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  resources :users

  root 'items#index'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'

  post '/users' => 'users#create'

  get "newcomments" => "items#newcomments"

  get "submit" => "items#submit"

  get "/v0/item/" => "apiv0#show"

  post "/v0/item/create" => "apiv0#create"

  get '/about' => 'pages#about'

  resources :apiv0, :path => '/v0/item/'  do
    resources :v0, controller: :apiv0
  end
  resources :items, :path => 'news'  do
   resources :posts, controller: :items, type: 'Post'
   resources :comments, controller: :items, type: 'Comment'
 end
end

rmit-news/app/models/item.rb
class Item < ApplicationRecord

  def by
    user.username
  end

  def time
    time = created_at.to_i
  end
end

rmit-news/app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # rails g controller items new newcomments submit index show
  # This controlleris used for items, a single table inheritance
  # It is used to view posts and comments, create them and yeah that's'
  # it

  def new
  end

  # Gets list of comments from newest to oldest
  def newcomments
    @comments = Item.where(type: "Comment").order("id DESC")
  end

  # Most of the data is sent from the form but some has to be added in
  # Like type and user id from the session. Then it was saved
  def create
    item = Item.new(item_params)
    item.user_id = current_user.id
    if params.has_key?(:comment)
      item.type = "Comment"
      item.save
      redirect_back(fallback_location: root_path)
    elsif params.has_key?(:post)
      item.type = "Post"
      item.save
      redirect_to '/'
    end
  end

  def submit
  end

  # Gets list of posts from newest to oldest
  def index
    @page = 0
    if params.has_key?(:p)
      @page = params[:p]
    end
    @prevpage = @page.to_i-1
    @nextpage = @page.to_i+1
    offset = @page*2
    @thenews = Item.where(type: "Post").order("id DESC").limit(10).offset(offset)

    if @thenews.count < 10
      @nextpage = nil
    end
    if @prevpage < 0
      @prevpage = nil
    end
  end

  # Finds the id of the the post which is requested in get
  def show
    @item = Item.find(params[:id])
  end

  # Tells which params should be accepted so they dont break the database
  private
    def item_params
      if params.has_key?(:comment)
        params.require(:comment).permit(:text, :post_id)
      elsif params.has_key?(:post)
        params.require(:post).permit(:text, :title, :url)
      end
    end
end

rmit-news/app/helpers/item_helper.rb
module ItemHelper
  def commentText(count)
    if count == 0
      text = "0 comments"
    else
      text = "#{count} comments"
    end
  end
end

rmit-news/app/views/items/create.html.erb
<h1>Item#create</h1>
<p>Find me in app/views/item/create.html.erb</p>

rmit-news/app/views/items/index.html.erb
  <h1 class="centereText fwTopmargin col-xs-12">All news</h1>
  <% @thenews.each do |news|%>
    <div class="col-xs-12">
      <div class="new_post_container white">
        <div class="contentIndent">
          <h4 class="new_post_title" style="margin-bottom: 8px;"><%= link_to news.title, news.url%></h4>
          <p class="subtext"> posted by <b> <%= news.user.username%> </b> at <%= localizedDate(news.created_at)%> <br> <b><%= link_to "comments: #{news.comments.count}", item_path(news)%></b></p>
        </div>
      </div>
    </div>
  <% end%>


<div id="pagers" class="bottom_nav">
  <!-- <span>Go to: </span> -->
  <%if !@prevpage.nil?%>
    <span><%= link_to "Previous ", root_path(:p => @prevpage)%></span>
  <%end%>
  <%if !@nextpage.nil?%>
  <!-- <span><%= link_to "Previous", root_path(:p => @prevpage)%></span> -->
    <span><%= link_to "More", root_path(:p => @nextpage) %></span>
  <% else %>
    <!-- <span>This is the last page</span> -->
  <%end%>
  <!-- <h3>Page: <%= @page%></h3> -->
</div>

rmit-news/app/views/items/new.html.erb
<h1>Item#new</h1>
<p>Find me in app/views/item/new.html.erb</p>

rmit-news/app/views/items/newcomments.html.erb
<h1 class="centereText fwTopmargin col-xs-12">Recent comments</h1>
<% @comments.each do |theComments| %>
  <div class="new_comment_container col-md-8 col-md-offset-2 col-xs-12 centereText">
    <p style="margin-bottom:0;">
      <b> <%= theComments.user.username%> </b>
      commented <br>
      " <i class="commentBlue"><%= theComments.text%></i> "
    </p>
    <p class="dib">on &nbsp;<p class='inlineArefRed'> <%= link_to theComments.post.title, item_path(theComments.post)%></p> &nbsp; <%= prettyDate(theComments.created_at)%></p>
  </div>
<%end%>

rmit-news/app/views/items/show.html.erb
<div class="posts_container">
  <div class="col-xs-12 fwTopmargin">
    <div class="new_post_container white">
      <div class="contentIndent">
        <h2 class="post_title"><%= link_to @item.title, @item.url%></h2>
        <!-- <p><%= @item.text%></p> -->
        <p> posted by <b> <%= @item.user.username%></b> <%= prettyDate(@item.created_at)%> | <%= commentText(@item.comments.count)%>  </p>
      </div>
    </div>
  </div>

  <!-- <% if @item.comments.count == 0%>
  <h4 class=" comment_header indent_comment col-xs-8" style="margin-top: 40px;">Viewing comments for <br> <b><i><%= @item.title %></i></b><br> but theres no comments here, be the first to comment</h4>
  <%elsif @item.comments.count > 0%>
  <h4 class=" comment_header indent_comment col-xs-8">Viewing <%= @item.comments.count%> comments for <br> <b><i><%= @item.title %></i></b></h4>
  <%end%> -->
  <div class=" col-md-8 col-xs-12">
    <div class="comment_box">
      <% if @item.comments.count == 0%>
      <p class="centereText" style="line-height:40px;"> There's no comments it's lonely down here :( </p>
      <%end%>
        <% @item.comments.each do |comments| %>
        <div class="comment_container">
          <p class="comment_text"><%= comments.text%></p>
          <p class="subsize"> commented by <%= comments.user.username%>, <i><%=prettyDate(comments.created_at)%></p></i>
        </div>
        <%end%>
      </div>
    </div>
    <div class="comments_container col-xs-12 col-md-4" id='commentonapost' style="min-height:190px;">
      <h4 class="centereText"> <b>Post a comment</b></h4>
      <% if current_user %>
        <%= form_for :comment, url: '/news' do |f|%>
          <%= f.hidden_field :post_id, value: @item.id%>
          <%= f.text_area :text%>
          <div style="width:100%;" class="centereText">
          <%= f.submit 'Post comment'%>
          </div>
        <%end%>
      <%else%>
      <div class="w-100">
        <img class="stopsign" src="https://61978.apps.zdusercontent.com/61978/assets/1506471217-f11f72e1d66993b37ef07602ecff83f2/logo.png" alt="">
      </div>
      <br>
        <h5 class="centereText"><%= link_to 'You need to be signed in to comment, please click to login', '/login' %> </h5>
      <%end%>
    </div>
</div>

rmit-news/app/views/items/submit.html.erb
  <% if current_user %>
    <%= form_for :post, url: '/news' do |f|%>
    <div class="container">
    	<div class="row">
    		<div class="col-md-8 col-md-offset-2 text-center">
    			<div class="search-box">
    				<div class="caption">
    					<h3>Create new post</h3>
    				</div>
    				<div class="loginForm col-xs-12">
    					<div class="input-group w-100" >
                <%= form_tag "/login" do %>
                  <div class="loginFields" >
                    <div class="labelW">
                      <span>Title:</span>
                    </div>
                    <div class="inputW">
                      <%= f.text_field :title%>
                    </div>
                  </div>
                  <div class="loginFields" >
                    <div class="labelW">
                      <span>Url:</span>
                    </div>
                    <div class="inputW">
                      <%= f.text_field :url%>
                    </div>
                  </div>
                  <!-- <div class="loginFields" style="margin-bottom:20px;">
                    <div class="labelW labelw__f">
                      <span>Description:</span>
                    </div>
                    <div class="inputW">
                      <%= f.text_area :text%>
                    </div>
                  </div> -->
                  <%= f.submit 'Post News'%>
                <%end%>
    					</div>
    				</div>
    			</div>
    		</div>
      </div>
    </div>
  <%end%>
  <%else%>
    <div class="w-100">
      <img class="stopsign" src="https://61978.apps.zdusercontent.com/61978/assets/1506471217-f11f72e1d66993b37ef07602ecff83f2/logo.png" alt="">
    </div>
    <div class="loginNotice">
      <%= link_to 'You need to be signed in to submit news, please click to login', '/login' %>
    </div>
  <%end%>